spring:
  profiles:
    include: secret
    active: prod

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "jinga3000@gmail.com"
    password: "kttvjkdaktqmjyyr"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true