name: Spring Boot & Gradle CI

on:
  push:
    branches: [ 'main', 'develop' ]
    pull_request: [ 'main', 'develop' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Git Secret을 이용한 application-xxx.yml 생성
      - name: Set Secret yml
        run:
          echo $SECRET_YML | base64 --decode > src/main/resources/application-secret.yml &&
          echo $PROD_YML | base64 --decode > src/main/resources/application-prod.yml
        env:
          SECRET_YML: ${{ secrets.SECRET_YML }}
          PROD_YML: ${{ secrets.PROD_YML }}

      # gradlew에 대한 권한 부여
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

